### ISSUE TITLE
Make a navigation bar.

### ISSUE THREAD

**Issue by shaykhsiddique** [shaykhsiddique/Online-Judge-servlet-java#4]
Make a navigation bar using ```bootstrap4```. 
The navigation bar will contain the list of

Left Middle side:-
- **Contests**
- **Problems**
- **SUBMISSIONS**
- **About** 

Right Side:-
- **Register**
- **Login**

must use these classes.
```html
<nav class="navbar navbar-default navbar-fixed-top navbar_style">
</nav>
```

**Comment by shaykhsiddique** [comment]
@jannatsorna 

Fix all of this.


> Why you use this ?

```html 
<div class="application-main">  
```
I think it is not need here.

> Why `container-fluid` is under `navbar` class ?
```html
<div class="container-fluid">
```
Not good to use in this way.
> You have no right to modify **body** `css` class
```css
body 
 {
   font-family:"Segoe UI";
   font-size: 1.45rem;
   font-weight: 500;
 }
```
Remove this, and find another way.

> **li:hover** will modify all list hover in whole website, which I do not want.
```css
li:hover 
 {
   background-color:#AB47BC;
   color: black;
 }
```
make this class more spacific.

> It's not working.
```css
@media only screen and (min-width:600px)
 {
    .talent
    {
        width: 32%;
    }
 }
```
Make it working.
